"exchanges": [
  {
    "name":"BR FUT",
    "open":"09:00",
    "close":"17:00"
  },
  {
    "name":"BR IBOV",
    "open":"10:00",
    "close":"17:30"
  },
  {
    "name":"US NYSE",
    "open":"10:30",
    "close":"17:00"
  },  
  {
    "name":"|OPER| NASDAQ",
    "open":"11:00",
    "close":"11:40"
  },   
]